### ISSUE TITLE
[Bug]: Modules > Card View Name update

### ISSUE THREAD

**Issue by B3nz01d** [Orange-OpenSource/ods-ios#235]
### Prerequisites

- [X] I have [searched the backlog](https://github.com/Orange-OpenSource/ods-ios/issues) for duplicate or closed feature requests

### Your test device

NA

### OS Version

NA

### App version

0.5.0

### Describe the issue

in #103 the request was updated to change the name of the module to "Card collections", but the name in now "Card View"
in #219 the change request was for the 2 locations where the name appears and it was change in only one

### Expected Behavior

change the name of the module to "Card collections" **in the card selection of the modules page** --and in the module page title--.

**Comment by Tayebsed93** [comment]
**Text magnification** : We recommend not to put a fixed size in the _"grid card"_ because the text is truncated once the text is enlarged
**Voice Over** : Also be careful not to vocalize the image with Voice Over
![IMG_0E7F1DA72D73-1](https://user-images.githubusercontent.com/20354434/198999114-87421f0b-b0ad-4fe4-9787-9a854225df2b.jpeg)

**Comment by B3nz01d** [comment]
both issue raised are closed
